### 1.import libraries

In [45]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

## 2.import data Set

In [17]:
load_breast_cancer()

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [16]:
breast_cancer_data=load_breast_cancer()

In [21]:
breast_cancer_df=pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [22]:
breast_cancer_df["Target"]=breast_cancer_data.target

In [23]:
breast_cancer_df

     mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0          17.99         10.38          122.80  ...          0.4601                  0.11890       0
1          20.57         17.77          132.90  ...          0.2750                  0.08902       0
2          19.69         21.25          130.00  ...          0.3613                  0.08758       0
3          11.42         20.38           77.58  ...          0.6638                  0.17300       0
4          20.29         14.34          135.10  ...          0.2364                  0.07678       0
..           ...           ...             ...  ...             ...                      ...     ...
564        21.56         22.39          142.00  ...          0.2060                  0.07115       0
565        20.13         28.25          131.20  ...          0.2572                  0.06637       0
566        16.60         28.08          108.30  ...          0.2218                  0.07820       0
567        20.60         29.33          140.10  ...          0.4087                  0.12400       0
568         7.76         24.54           47.92  ...          0.2871                  0.07039       1

[569 rows x 31 columns]

## 3. Data Understanding

In [24]:
breast_cancer_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [26]:
breast_cancer_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

## 4.Data Preparation

In [28]:
X=breast_cancer_df.drop(columns="Target",axis=1)
X

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [62]:
y=breast_cancer_df["Target"]
y.value_counts()

Target
1    357
0    212
Name: count, dtype: int64

In [31]:
std_scaler=StandardScaler()
scaled_X=std_scaler.fit_transform(X)
scaled_X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]], shape=(569, 30))

In [33]:
X_train, X_test, y_train, y_test=train_test_split(scaled_X,y,test_size=0.20,random_state=123,shuffle=True,stratify=y)

In [35]:
X_train.shape,y_train.shape

((455, 30), (455,))

In [36]:
X_test.shape,y_test.shape

((114, 30), (114,))

## 5.Model Building

In [58]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier= GradientBoostingClassifier(n_estimators=150,max_depth=1)
gb_classifier.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=1, n_estimators=150)

## 6.Model Training and 7.Model Evaluaton

### Training Data

In [69]:
y_pred_train=gb_classifier.predict(X_train)
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       170
           1       0.99      1.00      0.99       285

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

[[167   3]
 [  0 285]]

## Testing Data

In [49]:
y_pred_test = gb_classifier.predict(X_test)

In [57]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96        42
           1       0.99      0.97      0.98        72

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

In [52]:
print(confusion_matrix(y_test,y_pred_test))

[[41  1]
 [ 2 70]]

## =============================================================================================
XGBOOST ALGORITHM

In [63]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
     ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
     -------------------------------------- 0.0/101.7 MB 991.0 kB/s eta 0:01:43
     ---------------------------------------- 0.2/101.7 MB 1.5 MB/s eta 0:01:07
     ---------------------------------------- 0.4/101.7 MB 2.6 MB/s eta 0:00:40
     ---------------------------------------- 0.5/101.7 MB 2.6 MB/s eta 0:00:40
     ---------------------------------------- 0.6/101.7 MB 2.5 MB/s eta 0:00:40
     ---------------------------------------- 0.8/101.7 MB 2.8 MB/s eta 0:00:36
     ---------------------------------------- 1.0/101.7 MB 2.9 MB/s eta 0:00:35
      --------------------------------------- 1.5/101.7 MB 3.9 MB/s eta 0:00:26
      --------------------------------------- 1.8/101.7 MB 4.1 MB/s eta 0:00:25
      --------------------------------------- 2.0/101.7 MB 4.3 MB/s eta 0:00:24
      --------------------------------------- 2.4/101.7 MB 4.6 MB/s eta 0:00:22
     - -------------------------------------- 2.6/101.7 MB 4.5 MB/s eta 0:00:23
     - -------------------------------------- 2.9/101.7 MB 4.6 MB/s eta 0:00:22
     - -------------------------------------- 3.0/101.7 MB 4.6 MB/s eta 0:00:22
     - -------------------------------------- 3.2/101.7 MB 4.6 MB/s eta 0:00:22
     - -------------------------------------- 3.3/101.7 MB 4.3 MB/s eta 0:00:23
     - -------------------------------------- 3.4/101.7 MB 4.3 MB/s eta 0:00:24
     - -------------------------------------- 3.4/101.7 MB 4.3 MB/s eta 0:00:24
     - -------------------------------------- 3.4/101.7 MB 4.3 MB/s eta 0:00:24
     - -------------------------------------- 3.4/101.7 MB 4.3 MB/s eta 0:00:24
     - -------------------------------------- 3.4/101.7 MB 4.3 MB/s eta 0:00:24
     - -------------------------------------- 3.8/101.7 MB 3.7 MB/s eta 0:00:27
     - -------------------------------------- 4.4/101.7 MB 4.2 MB/s eta 0:00:24
     - -------------------------------------- 4.7/101.7 MB 4.2 MB/s eta 0:00:23
     - -------------------------------------- 5.0/101.7 MB 4.3 MB/s eta 0:00:23
     -- ------------------------------------- 5.7/101.7 MB 4.7 MB/s eta 0:00:21
     -- ------------------------------------- 6.1/101.7 MB 4.8 MB/s eta 0:00:20
     -- ------------------------------------- 6.6/101.7 MB 5.0 MB/s eta 0:00:20
     -- ------------------------------------- 6.7/101.7 MB 5.0 MB/s eta 0:00:19
     -- ------------------------------------- 6.8/101.7 MB 4.9 MB/s eta 0:00:20
     -- ------------------------------------- 7.0/101.7 MB 4.9 MB/s eta 0:00:20
     -- ------------------------------------- 7.1/101.7 MB 4.8 MB/s eta 0:00:20
     -- ------------------------------------- 7.5/101.7 MB 4.8 MB/s eta 0:00:20
     -- ------------------------------------- 7.6/101.7 MB 4.8 MB/s eta 0:00:20
     --- ------------------------------------ 7.7/101.7 MB 4.7 MB/s eta 0:00:21
     --- ------------------------------------ 7.9/101.7 MB 4.7 MB/s eta 0:00:21
     --- ------------------------------------ 8.1/101.7 MB 4.7 MB/s eta 0:00:21
     --- ------------------------------------ 8.2/101.7 MB 4.7 MB/s eta 0:00:21
     --- ------------------------------------ 8.3/101.7 MB 4.5 MB/s eta 0:00:21
     --- ------------------------------------ 8.4/101.7 MB 4.5 MB/s eta 0:00:21
     --- ------------------------------------ 8.5/101.7 MB 4.4 MB/s eta 0:00:22
     --- ------------------------------------ 8.6/101.7 MB 4.4 MB/s eta 0:00:22
     --- ------------------------------------ 8.7/101.7 MB 4.3 MB/s eta 0:00:22
     --- ------------------------------------ 8.8/101.7 MB 4.3 MB/s eta 0:00:22
     --- ------------------------------------ 8.9/101.7 MB 4.2 MB/s eta 0:00:22
     --- ------------------------------------ 9.0/101.7 MB 4.2 MB/s eta 0:00:23
     --- ------------------------------------ 9.1/101.7 MB 4.1 MB/s eta 0:00:23
     --- ------------------------------------ 9.2/101.7 MB 4.1 MB/s eta 0:00:23
     --- ------------------------------------ 9.3/101.7 MB 4.0 MB/s eta 0:00:23
     --- ------------------------------------ 9.4/101.7 MB 4.0 MB/s eta 0:00:24
     --- ------------------------------------ 9.4/101.7 MB 3.9 MB/s eta 0:00:24
     --- ------------------------------------ 9.5/101.7 MB 3.9 MB/s eta 0:00:24
     --- ------------------------------------ 9.5/101.7 MB 3.8 MB/s eta 0:00:25
     --- ------------------------------------ 9.6/101.7 MB 3.6 MB/s eta 0:00:26
     --- ------------------------------------ 9.6/101.7 MB 3.6 MB/s eta 0:00:26
     --- ------------------------------------ 9.6/101.7 MB 3.5 MB/s eta 0:00:27
     --- ------------------------------------ 9.7/101.7 MB 3.4 MB/s eta 0:00:27
     --- ------------------------------------ 9.7/101.7 MB 3.4 MB/s eta 0:00:27
     --- ------------------------------------ 9.7/101.7 MB 3.3 MB/s eta 0:00:28
     --- ------------------------------------ 9.7/101.7 MB 3.3 MB/s eta 0:00:28
     --- ------------------------------------ 9.8/101.7 MB 3.3 MB/s eta 0:00:29
     --- ------------------------------------ 9.9/101.7 MB 3.2 MB/s eta 0:00:29
     --- ----------------------------------- 10.0/101.7 MB 3.2 MB/s eta 0:00:29
     --- ----------------------------------- 10.1/101.7 MB 3.2 MB/s eta 0:00:29
     --- ----------------------------------- 10.2/101.7 MB 3.2 MB/s eta 0:00:29
     --- ----------------------------------- 10.3/101.7 MB 3.3 MB/s eta 0:00:29
     ---- ---------------------------------- 10.4/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 10.6/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 10.7/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 10.8/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 10.9/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 11.0/101.7 MB 3.2 MB/s eta 0:00:29
     ---- ---------------------------------- 11.0/101.7 MB 3.1 MB/s eta 0:00:29
     ---- ---------------------------------- 11.1/101.7 MB 3.1 MB/s eta 0:00:30
     ---- ---------------------------------- 11.2/101.7 MB 3.1 MB/s eta 0:00:30
     ---- ---------------------------------- 11.3/101.7 MB 3.0 MB/s eta 0:00:30
     ---- ---------------------------------- 11.4/101.7 MB 3.0 MB/s eta 0:00:30
     ---- ---------------------------------- 11.5/101.7 MB 3.0 MB/s eta 0:00:31
     ---- ---------------------------------- 11.6/101.7 MB 2.9 MB/s eta 0:00:31
     ---- ---------------------------------- 11.6/101.7 MB 2.9 MB/s eta 0:00:31
     ---- ---------------------------------- 11.7/101.7 MB 2.9 MB/s eta 0:00:32
     ---- ---------------------------------- 11.8/101.7 MB 2.8 MB/s eta 0:00:32
     ---- ---------------------------------- 11.9/101.7 MB 2.8 MB/s eta 0:00:32
     ---- ---------------------------------- 11.9/101.7 MB 2.8 MB/s eta 0:00:33
     ---- ---------------------------------- 11.9/101.7 MB 2.8 MB/s eta 0:00:33
     ---- ---------------------------------- 11.9/101.7 MB 2.8 MB/s eta 0:00:33
     ---- ---------------------------------- 12.0/101.7 MB 2.7 MB/s eta 0:00:34
     ---- ---------------------------------- 12.0/101.7 MB 2.7 MB/s eta 0:00:34
     ---- ---------------------------------- 12.0/101.7 MB 2.6 MB/s eta 0:00:34
     ---- ---------------------------------- 12.1/101.7 MB 2.6 MB/s eta 0:00:35
     ---- ---------------------------------- 12.2/101.7 MB 2.6 MB/s eta 0:00:35
     ---- ---------------------------------- 12.2/101.7 MB 2.6 MB/s eta 0:00:35
     ---- ---------------------------------- 12.2/101.7 MB 2.5 MB/s eta 0:00:36
     ---- ---------------------------------- 12.4/101.7 MB 2.5 MB/s eta 0:00:36
     ---- ---------------------------------- 12.4/101.7 MB 2.5 MB/s eta 0:00:36
     ---- ---------------------------------- 12.6/101.7 MB 2.5 MB/s eta 0:00:36
     ---- ---------------------------------- 12.7/101.7 MB 2.5 MB/s eta 0:00:37
     ---- ---------------------------------- 12.8/101.7 MB 2.5 MB/s eta 0:00:37
     ---- ---------------------------------- 12.9/101.7 MB 2.4 MB/s eta 0:00:37
     ---- ---------------------------------- 13.0/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 13.1/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 13.3/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 13.4/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 13.5/101.7 MB 2.4 MB/s eta 0:00:38
     ----- --------------------------------- 13.6/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 13.7/101.7 MB 2.5 MB/s eta 0:00:36
     ----- --------------------------------- 13.9/101.7 MB 2.5 MB/s eta 0:00:36
     ----- --------------------------------- 14.0/101.7 MB 2.4 MB/s eta 0:00:36
     ----- --------------------------------- 14.2/101.7 MB 2.4 MB/s eta 0:00:36
     ----- --------------------------------- 14.3/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 14.5/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 14.7/101.7 MB 2.4 MB/s eta 0:00:37
     ----- --------------------------------- 14.8/101.7 MB 2.3 MB/s eta 0:00:38
     ----- --------------------------------- 14.9/101.7 MB 2.3 MB/s eta 0:00:38
     ----- --------------------------------- 15.1/101.7 MB 2.3 MB/s eta 0:00:38
     ----- --------------------------------- 15.2/101.7 MB 2.3 MB/s eta 0:00:38
     ----- --------------------------------- 15.3/101.7 MB 2.3 MB/s eta 0:00:38
     ----- --------------------------------- 15.4/101.7 MB 2.3 MB/s eta 0:00:39
     ----- --------------------------------- 15.4/101.7 MB 2.2 MB/s eta 0:00:39
     ----- --------------------------------- 15.5/101.7 MB 2.2 MB/s eta 0:00:39
     ----- --------------------------------- 15.6/101.7 MB 2.2 MB/s eta 0:00:40
     ------ -------------------------------- 15.7/101.7 MB 2.2 MB/s eta 0:00:40
     ------ -------------------------------- 15.7/101.7 MB 2.2 MB/s eta 0:00:40
     ------ -------------------------------- 15.8/101.7 MB 2.1 MB/s eta 0:00:41
     ------ -------------------------------- 15.8/101.7 MB 2.1 MB/s eta 0:00:41
     ------ -------------------------------- 15.9/101.7 MB 2.1 MB/s eta 0:00:41
     ------ -------------------------------- 16.0/101.7 MB 2.1 MB/s eta 0:00:42
     ------ -------------------------------- 16.2/101.7 MB 2.1 MB/s eta 0:00:42
     ------ -------------------------------- 16.3/101.7 MB 2.1 MB/s eta 0:00:42
     ------ -------------------------------- 16.3/101.7 MB 2.0 MB/s eta 0:00:42
     ------ -------------------------------- 16.4/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 16.6/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 16.6/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 16.8/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 16.9/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.1/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.3/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.5/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.6/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.7/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.7/101.7 MB 2.0 MB/s eta 0:00:43
     ------ -------------------------------- 17.8/101.7 MB 1.9 MB/s eta 0:00:44
     ------ -------------------------------- 17.9/101.7 MB 1.9 MB/s eta 0:00:44
     ------ -------------------------------- 18.0/101.7 MB 1.9 MB/s eta 0:00:44
     ------ -------------------------------- 18.1/101.7 MB 1.9 MB/s eta 0:00:44
     ------- ------------------------------- 18.3/101.7 MB 1.9 MB/s eta 0:00:44
     ------- ------------------------------- 18.4/101.7 MB 1.9 MB/s eta 0:00:43
     ------- ------------------------------- 18.5/101.7 MB 1.9 MB/s eta 0:00:44
     ------- ------------------------------- 18.6/101.7 MB 1.9 MB/s eta 0:00:43
     ------- ------------------------------- 18.8/101.7 MB 1.9 MB/s eta 0:00:43
     ------- ------------------------------- 18.9/101.7 MB 1.9 MB/s eta 0:00:43
     ------- ------------------------------- 19.1/101.7 MB 2.0 MB/s eta 0:00:43
     ------- ------------------------------- 19.2/101.7 MB 2.0 MB/s eta 0:00:43
     ------- ------------------------------- 19.3/101.7 MB 2.0 MB/s eta 0:00:43
     ------- ------------------------------- 19.4/101.7 MB 2.0 MB/s eta 0:00:42
     ------- ------------------------------- 19.5/101.7 MB 2.0 MB/s eta 0:00:42
     ------- ------------------------------- 19.6/101.7 MB 2.0 MB/s eta 0:00:42
     ------- ------------------------------- 19.7/101.7 MB 2.0 MB/s eta 0:00:41
     ------- ------------------------------- 19.9/101.7 MB 2.1 MB/s eta 0:00:39
     ------- ------------------------------- 20.0/101.7 MB 2.2 MB/s eta 0:00:38
     ------- ------------------------------- 20.1/101.7 MB 2.2 MB/s eta 0:00:38
     ------- ------------------------------- 20.3/101.7 MB 2.2 MB/s eta 0:00:38
     ------- ------------------------------- 20.4/101.7 MB 2.2 MB/s eta 0:00:37
     ------- ------------------------------- 20.6/101.7 MB 2.2 MB/s eta 0:00:37
     ------- ------------------------------- 20.8/101.7 MB 2.2 MB/s eta 0:00:37
     -------- ------------------------------ 21.0/101.7 MB 2.2 MB/s eta 0:00:37
     -------- ------------------------------ 21.1/101.7 MB 2.2 MB/s eta 0:00:36
     -------- ------------------------------ 21.3/101.7 MB 2.3 MB/s eta 0:00:35
     -------- ------------------------------ 21.5/101.7 MB 2.3 MB/s eta 0:00:35
     -------- ------------------------------ 21.6/101.7 MB 2.3 MB/s eta 0:00:35
     -------- ------------------------------ 21.8/101.7 MB 2.4 MB/s eta 0:00:34
     -------- ------------------------------ 22.0/101.7 MB 2.4 MB/s eta 0:00:34
     -------- ------------------------------ 22.1/101.7 MB 2.5 MB/s eta 0:00:33
     -------- ------------------------------ 22.3/101.7 MB 2.6 MB/s eta 0:00:32
     -------- ------------------------------ 22.4/101.7 MB 2.6 MB/s eta 0:00:31
     -------- ------------------------------ 22.6/101.7 MB 2.6 MB/s eta 0:00:31
     -------- ------------------------------ 22.8/101.7 MB 2.6 MB/s eta 0:00:30
     -------- ------------------------------ 23.0/101.7 MB 2.7 MB/s eta 0:00:30
     -------- ------------------------------ 23.1/101.7 MB 2.7 MB/s eta 0:00:30
     -------- ------------------------------ 23.3/101.7 MB 2.7 MB/s eta 0:00:30
     --------- ----------------------------- 23.5/101.7 MB 2.7 MB/s eta 0:00:29
     --------- ----------------------------- 23.7/101.7 MB 2.8 MB/s eta 0:00:29
     --------- ----------------------------- 23.9/101.7 MB 2.8 MB/s eta 0:00:29
     --------- ----------------------------- 24.0/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 24.1/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 24.2/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 24.4/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 24.7/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 24.9/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.0/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.0/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.2/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.2/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.5/101.7 MB 2.8 MB/s eta 0:00:28
     --------- ----------------------------- 25.7/101.7 MB 2.9 MB/s eta 0:00:27
     --------- ----------------------------- 25.8/101.7 MB 2.9 MB/s eta 0:00:27
     --------- ----------------------------- 26.0/101.7 MB 2.9 MB/s eta 0:00:26
     ---------- ---------------------------- 26.1/101.7 MB 3.0 MB/s eta 0:00:26
     ---------- ---------------------------- 26.3/101.7 MB 3.0 MB/s eta 0:00:25
     ---------- ---------------------------- 26.5/101.7 MB 3.1 MB/s eta 0:00:25
     ---------- ---------------------------- 26.7/101.7 MB 3.1 MB/s eta 0:00:25
     ---------- ---------------------------- 26.8/101.7 MB 3.1 MB/s eta 0:00:25
     ---------- ---------------------------- 27.0/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.1/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.3/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.5/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.6/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.8/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 27.9/101.7 MB 3.1 MB/s eta 0:00:24
     ---------- ---------------------------- 28.1/101.7 MB 3.2 MB/s eta 0:00:23
     ---------- ---------------------------- 28.3/101.7 MB 3.3 MB/s eta 0:00:23
     ---------- ---------------------------- 28.5/101.7 MB 3.3 MB/s eta 0:00:23
     ---------- ---------------------------- 28.7/101.7 MB 3.3 MB/s eta 0:00:22
     ----------- --------------------------- 28.8/101.7 MB 3.3 MB/s eta 0:00:22
     ----------- --------------------------- 29.0/101.7 MB 3.4 MB/s eta 0:00:22
     ----------- --------------------------- 29.1/101.7 MB 3.4 MB/s eta 0:00:22
     ----------- --------------------------- 29.3/101.7 MB 3.3 MB/s eta 0:00:22
     ----------- --------------------------- 29.4/101.7 MB 3.3 MB/s eta 0:00:22
     ----------- --------------------------- 29.6/101.7 MB 3.4 MB/s eta 0:00:22
     ----------- --------------------------- 29.8/101.7 MB 3.4 MB/s eta 0:00:21
     ----------- --------------------------- 29.9/101.7 MB 3.4 MB/s eta 0:00:22
     ----------- --------------------------- 30.1/101.7 MB 3.4 MB/s eta 0:00:22
     ----------- --------------------------- 30.3/101.7 MB 3.4 MB/s eta 0:00:21
     ----------- --------------------------- 30.4/101.7 MB 3.5 MB/s eta 0:00:21
     ----------- --------------------------- 30.6/101.7 MB 3.5 MB/s eta 0:00:21
     ----------- --------------------------- 30.8/101.7 MB 3.5 MB/s eta 0:00:21
     ----------- --------------------------- 30.9/101.7 MB 3.5 MB/s eta 0:00:21
     ----------- --------------------------- 31.1/101.7 MB 3.5 MB/s eta 0:00:21
     ------------ -------------------------- 31.3/101.7 MB 3.5 MB/s eta 0:00:21
     ------------ -------------------------- 31.5/101.7 MB 3.5 MB/s eta 0:00:21
     ------------ -------------------------- 31.7/101.7 MB 3.5 MB/s eta 0:00:21
     ------------ -------------------------- 31.9/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.2/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.4/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.5/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.6/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.8/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 32.9/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 33.0/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 33.2/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 33.2/101.7 MB 3.5 MB/s eta 0:00:20
     ------------ -------------------------- 33.3/101.7 MB 3.4 MB/s eta 0:00:21
     ------------ -------------------------- 33.3/101.7 MB 3.4 MB/s eta 0:00:20
     ------------ -------------------------- 33.4/101.7 MB 3.3 MB/s eta 0:00:21
     ------------ -------------------------- 33.5/101.7 MB 3.3 MB/s eta 0:00:21
     ------------ -------------------------- 33.5/101.7 MB 3.3 MB/s eta 0:00:21
     ------------ -------------------------- 33.6/101.7 MB 3.3 MB/s eta 0:00:21
     ------------ -------------------------- 33.7/101.7 MB 3.2 MB/s eta 0:00:21

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import xgboost as xgb

In [66]:
xgb_classifier=xgb.XGBClassifier()

In [67]:
xgb_classifier.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [68]:
xgb_classifier.predict(X_train)

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [73]:
y_pred_train=xgb_classifier.predict(X_train)
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       170
           1       1.00      1.00      1.00       285

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455

[[170   0]
 [  0 285]]

In [74]:
y_pred_test=xgb_classifier.predict(X_test)
print(classification_report(y_test,y_pred_test))
print(confusion_matrix(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        42
           1       1.00      0.99      0.99        72

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

[[170   0]
 [  0 285]]