## DATA PREPROCESSING AND PREPARATION

1.Data Cleaning - drop,fillna with mean,median,mode computation, changing dtype

2.Data Transformation

    * If data is CONTINOUS = Standard Scaler,MinMaxScaler,Robust Scaler
    
    * If data is DISCRETE = Label Encoder,One HOT Encoder

## 1.Import required libraries

In [1]:
import pandas as pd

## 2.Data Collection

In [52]:
environmental_data = pd.read_csv("environmental_data.csv")
environmental_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3.Data Understanding

In [53]:
environmental_data.shape

(158, 10)

In [54]:
environmental_data.describe(include = "all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [55]:
environmental_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [56]:
environmental_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [57]:
environmental_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [58]:
environmental_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 4.Data Preparation

In [59]:
environmental_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

## 4.1 Data Cleaning - drop,fillna with mean,median,mode computation, changing dtype

In [60]:
environmental_data.drop(labels=["Unnamed: 0","Temp C"],axis=1,inplace=True)

In [61]:
environmental_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

### We removed 2 unwanted columns : "Unnamed: 0","Temp C"

In [62]:
environmental_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [63]:
38/158

0.24050632911392406

### I'm dropping this Ozone Column since it's having 25 % Nan

In [64]:
del environmental_data["Ozone"]

In [65]:
environmental_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [66]:
environmental_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [67]:
environmental_data[environmental_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [68]:
environmental_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [69]:
environmental_data["Solar.R"]=environmental_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))

In [70]:
environmental_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [73]:
environmental_data[environmental_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [74]:
environmental_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [79]:
environmental_data.dropna(inplace=True)

In [80]:
environmental_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [81]:
environmental_data.shape

(155, 7)

In [82]:
environmental_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [25]:
environmental_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [89]:
environmental_data["Month"].replace(to_replace="May",value=5,inplace=True)

C:\Users\sujin\AppData\Local\Temp\ipykernel_11120\417505155.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  environmental_data["Month"].replace(to_replace="May",value=5,inplace=True)

In [88]:
environmental_data["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [91]:
environmental_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [94]:
environmental_data["Month"]=environmental_data["Month"].astype("int")

In [95]:
environmental_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

## Stage 2 : Data Transformation

Data Transformation

    * If data is CONTINOUS = Standard Scaler,MinMaxScaler,Robust Scaler
    
    * If data is DISCRETE = Label Encoder,One HOT Encoder

In [96]:
environmental_data_copy1 = environmental_data.copy()

### 2.1. Label Encoding

In [98]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
environmental_data_copy1["Weather"] = le_encoder.fit_transform(environmental_data_copy1["Weather"])

In [99]:
environmental_data_copy1.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

### 2.2 OneHot Encoding
Ths can be achieved by using any of the following 2 libraries.

1.Pandas - pd.get_dummies()
2.sklearn - OneHotEncoder()

In [100]:
environmental_data_copy2=environmental_data_copy1.copy()

### Using pd.get_dummies()

In [102]:
environmental_data_copy2 = pd.get_dummies(data=environmental_data_copy2,columns=["Weather"],dtype="int")

In [103]:
environmental_data_copy2

     Solar.R  Wind  Month  Day  Year  Temp  Weather_0  Weather_1  Weather_2
0      190.0   7.4      5    1  2010    67          0          0          1
1      118.0   8.0      5    2  2010    72          1          0          0
2      149.0  12.6      5    3  2010    74          0          1          0
3      313.0  11.5      5    4  2010    62          0          0          1
4      193.0  14.3      5    5  2010    56          0          0          1
..       ...   ...    ...  ...   ...   ...        ...        ...        ...
153    190.0   7.4      5    1  2010    67          1          0          0
154    193.0   6.9      9   26  2010    70          0          1          0
155    145.0  13.2      9   27  2010    77          0          0          1
156    191.0  14.3      9   28  2010    75          0          0          1
157    131.0   8.0      9   29  2010    76          1          0          0

[155 rows x 9 columns]

### Using One Hot Encoder

In [132]:
environmental_data_copy3 = environmental_data.copy()

In [133]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Create encoder
ohe = OneHotEncoder(sparse_output=False)

# Encode the categorical column
encoded_data = ohe.fit_transform(environmental_data_copy3[['Weather']])

# Create a DataFrame with encoded columns
encoded_df = pd.DataFrame(
    encoded_data,
    columns=ohe.get_feature_names_out(['Weather']),
    index=environmental_data_copy3.index
)

# Drop original column and combine with encoded columns
environmental_data_copy3 = pd.concat(
    [environmental_data_copy1.drop('Weather', axis=1), encoded_df],
    axis=1
)

print(environmental_data_copy3.head())

   Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0    190.0   7.4      5    1  2010    67        0.0         0.0        1.0
1    118.0   8.0      5    2  2010    72        1.0         0.0        0.0
2    149.0  12.6      5    3  2010    74        0.0         1.0        0.0
3    313.0  11.5      5    4  2010    62        0.0         0.0        1.0
4    193.0  14.3      5    5  2010    56        0.0         0.0        1.0

In [134]:
environmental_data_copy3.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C     float64
Weather_PS    float64
Weather_S     float64
dtype: object