In [67]:
#Import libraries

import pandas as  pd
import warnings
warnings.filterwarnings("ignore")

In [44]:
# 1. Data Collection
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [5]:
# 2.Data Understanding
weather_data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [6]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [7]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [45]:
# Data Preprocessing

# removing unwanted columns

weather_data.drop(labels=["Unnamed: 0","Temp C"],axis=1,inplace=True)

In [10]:
weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [46]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [47]:
# Ozone Column is having almost 25 % Nan Data..So,removing it

del weather_data["Ozone"]

In [13]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [48]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [49]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [50]:
# we've 3 weather categories in Weather column. We can inpute the Solar.R column by imputing the mean

weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [51]:
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x: x.fillna(x.mean().round()))

In [52]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [53]:
weather_data.dropna(inplace=True)

In [54]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [55]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [56]:
weather_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [68]:
weather_data["Month"].replace(to_replace="May",value=5,inplace=True)

In [58]:
weather_data["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [59]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [60]:
weather_data["Month"]=weather_data["Month"].astype("int")

In [61]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [62]:
#Now all the Na entries are handled and all data types are numerical except weather.. Now using Label encode to label to Weather column

from sklearn.preprocessing import LabelEncoder
le_encoder=LabelEncoder()

weather_data["Weather"] = le_encoder.fit_transform(weather_data["Weather"])
weather_data

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [63]:
X = weather_data.drop(labels="Weather",axis=1)
X

     Solar.R  Wind  Month  Day  Year  Temp
0      190.0   7.4      5    1  2010    67
1      118.0   8.0      5    2  2010    72
2      149.0  12.6      5    3  2010    74
3      313.0  11.5      5    4  2010    62
4      193.0  14.3      5    5  2010    56
..       ...   ...    ...  ...   ...   ...
153    190.0   7.4      5    1  2010    67
154    193.0   6.9      9   26  2010    70
155    145.0  13.2      9   27  2010    77
156    191.0  14.3      9   28  2010    75
157    131.0   8.0      9   29  2010    76

[155 rows x 6 columns]

In [89]:
weather_data

     0  1  2
0    0  0  1
1    1  0  0
2    0  1  0
3    0  0  1
4    0  0  1
..  .. .. ..
153  1  0  0
154  0  1  0
155  0  0  1
156  0  0  1
157  1  0  0

[155 rows x 3 columns]

In [64]:
y=weather_data["Weather"]
y

0      2
1      0
2      1
3      2
4      2
      ..
153    0
154    1
155    2
156    2
157    0
Name: Weather, Length: 155, dtype: int64

In [71]:
# Train Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=34,shuffle=True)

In [74]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()

logistic_model.fit(X_train,y_train)

LogisticRegression()

In [78]:
y_pred_train = logistic_model.predict(X_train)

In [76]:
from sklearn.metrics import classification_report,confusion_matrix

In [80]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.37      0.26      0.31        38
           1       0.38      0.25      0.30        40
           2       0.39      0.61      0.48        46

    accuracy                           0.39       124
   macro avg       0.38      0.37      0.36       124
weighted avg       0.38      0.39      0.37       124

In [82]:
y_pred_test=logistic_model.predict(X_test)

In [83]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.23      0.27      0.25        11
           1       0.17      0.14      0.15         7
           2       0.42      0.38      0.40        13

    accuracy                           0.29        31
   macro avg       0.27      0.27      0.27        31
weighted avg       0.29      0.29      0.29        31

In [88]:
weather_data

     0  1  2
0    0  0  1
1    1  0  0
2    0  1  0
3    0  0  1
4    0  0  1
..  .. .. ..
153  1  0  0
154  0  1  0
155  0  0  1
156  0  0  1
157  1  0  0

[155 rows x 3 columns]

In [87]:
# OneHotEncoder Using pandas
weather_data=pd.get_dummies(data=weather_data,columns=["Weather"],dtype="int")
weather_data

KeyError: "None of [Index(['Weather'], dtype='object')] are in the [columns]"