## 1.Import required Libraries

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel,RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix

## 2.Data Collection

In [3]:
credit_card_data = pd.read_csv("credit_card_clean.csv")
credit_card_data

          ID  LIMIT_BAL     SEX   EDUCATION MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0          1    20000.0  female  university  married   24  ...     689.0       0.0       0.0       0.0       0.0        1
1          2   120000.0  female  university   single   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2          3    90000.0  female  university   single   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3          4    50000.0  female  university  married   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4          5    50000.0    male  university  married   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0
...      ...        ...     ...         ...      ...  ...  ...       ...       ...       ...       ...       ...      ...
29995  29996   220000.0    male  highschool  married   39  ...   20000.0    5003.0    3047.0    5000.0    1000.0        0
29996  29997   150000.0    male  highschool   single   43  ...    3526.0    8998.0     129.0       0.0       0.0        0
29997  29998    30000.0    male  university   single   37  ...       0.0   22000.0    4200.0    2000.0    3100.0        1
29998  29999    80000.0    male  highschool  married   41  ...    3409.0    1178.0    1926.0   52964.0    1804.0        1
29999  30000    50000.0    male  university  married   46  ...    1800.0    1430.0    1000.0    1000.0    1000.0        1

[30000 rows x 25 columns]

## 3.Data Understanding

In [4]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [5]:
credit_card_data.shape

(30000, 25)

In [8]:
credit_card_data.duplicated().sum()

np.int64(0)

## 4.Data Preparation

In [9]:
credit_card_data.drop(labels="ID",axis=1)

       LIMIT_BAL     SEX   EDUCATION MARRIAGE  AGE  PAY_1  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0        20000.0  female  university  married   24      2  ...     689.0       0.0       0.0       0.0       0.0        1
1       120000.0  female  university   single   26     -1  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2        90000.0  female  university   single   34      0  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3        50000.0  female  university  married   37      0  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4        50000.0    male  university  married   57     -1  ...   36681.0   10000.0    9000.0     689.0     679.0        0
...          ...     ...         ...      ...  ...    ...  ...       ...       ...       ...       ...       ...      ...
29995   220000.0    male  highschool  married   39      0  ...   20000.0    5003.0    3047.0    5000.0    1000.0        0
29996   150000.0    male  highschool   single   43     -1  ...    3526.0    8998.0     129.0       0.0       0.0        0
29997    30000.0    male  university   single   37      4  ...       0.0   22000.0    4200.0    2000.0    3100.0        1
29998    80000.0    male  highschool  married   41      1  ...    3409.0    1178.0    1926.0   52964.0    1804.0        1
29999    50000.0    male  university  married   46      0  ...    1800.0    1430.0    1000.0    1000.0    1000.0        1

[30000 rows x 24 columns]

In [17]:
l_encoder = LabelEncoder()
credit_card_data["SEX"]=l_encoder.fit_transform(credit_card_data.SEX)
credit_card_data["EDUCATION"]=l_encoder.fit_transform(credit_card_data.EDUCATION)
credit_card_data["MARRIAGE"]=l_encoder.fit_transform(credit_card_data.MARRIAGE)

credit_card_data

          ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0          1    20000.0    0          3         0   24  ...     689.0       0.0       0.0       0.0       0.0        1
1          2   120000.0    0          3         2   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2          3    90000.0    0          3         2   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3          4    50000.0    0          3         0   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4          5    50000.0    1          3         0   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0
...      ...        ...  ...        ...       ...  ...  ...       ...       ...       ...       ...       ...      ...
29995  29996   220000.0    1          1         0   39  ...   20000.0    5003.0    3047.0    5000.0    1000.0        0
29996  29997   150000.0    1          1         2   43  ...    3526.0    8998.0     129.0       0.0       0.0        0
29997  29998    30000.0    1          3         2   37  ...       0.0   22000.0    4200.0    2000.0    3100.0        1
29998  29999    80000.0    1          1         0   41  ...    3409.0    1178.0    1926.0   52964.0    1804.0        1
29999  30000    50000.0    1          3         0   46  ...    1800.0    1430.0    1000.0    1000.0    1000.0        1

[30000 rows x 25 columns]

In [22]:
X=credit_card_data.drop("DEFAULT",axis=1)
y=credit_card_data["DEFAULT"]

## 5.Model Building

In [23]:
X_train, X_test, y_train, y_test = train_test_split = train_test_split(X,y,test_size=0.20,random_state=123,shuffle=True)

In [26]:
X_train.shape,y_train.shape

((24000, 24), (24000,))

In [27]:
X_test.shape,y_test.shape

((6000, 24), (6000,))

## 6.Model Training

In [33]:
rf_classifier = RandomForestClassifier(max_depth=7)
rf_classifier.fit(X_train,y_train)

y_pred_train = rf_classifier.predict(X_train)

In [39]:
print("Accuracy Score:",round(accuracy_score(y_train,y_pred_train),4))
print("Precision Score:",round(precision_score(y_train,y_pred_train),4))
print("Recall Score:",round(recall_score(y_train,y_pred_train),4))
print("Confusion matrix:\n",(confusion_matrix(y_train,y_pred_train)))

Accuracy Score: 0.8311
Precision Score: 0.7408
Recall Score: 0.3687
Confusion matrix:
 [[17980   688]
 [ 3366  1966]]

In [40]:
rf_classifier.feature_importances_

array([0.01404983, 0.02372844, 0.00163473, 0.00252152, 0.00161757,
       0.01245363, 0.29092095, 0.15809013, 0.07889224, 0.07070467,
       0.05657849, 0.0666852 , 0.02166718, 0.01635443, 0.01355885,
       0.01425523, 0.01291392, 0.01288427, 0.03399868, 0.02839956,
       0.01996481, 0.01889742, 0.01617707, 0.01305119])

## Feature Engineering

### 1.SelectFromModel

In [41]:
sf_model = SelectFromModel(estimator=RandomForestClassifier(),max_features=None)
sf_model.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier())

In [43]:
len(sf_model.get_support())

24

In [62]:
X_train_select_from_model = sf_model.transform(X_train)
X_test_select_from_model = sf_model.transform(X_test)

In [63]:
X_train_select_from_model.shape,y_train_select_from_model.shape

((24000, 15), (6000, 15))

In [79]:
def RunRandomForestClassifier(X_train,y_train,X_test,y_test):
    rf_model = RandomForestClassifier(max_depth = 7,random_state=12)
    rf_model.fit(X_train,y_train)
    
    y_pred = rf_model.predict(X_test)


    print("Accuracy Score:",round(accuracy_score(y_test,y_pred),4))
    print("Precision Score:",round(precision_score(y_test,y_pred),4))
    print("Recall Score",round(recall_score(y_test,y_pred),4))
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

In [65]:
%%time

RunRandomForestClassifier(X_train,y_train,X_test,y_test)  # For 30 features

Accuracy Score: 0.8195
Precision Score: 0.6662
Recall Score 0.3397
Confusion Matrix:
 [[4474  222]
 [ 861  443]]
CPU times: total: 6.38 s
Wall time: 7.13 s

In [67]:
%%time

RunRandomForestClassifier(X_train_select_from_model,y_train,X_test_select_from_model,y_test)  # For 24 features

Accuracy Score: 0.823
Precision Score: 0.6891
Recall Score 0.3382
Confusion Matrix:
 [[4497  199]
 [ 863  441]]
CPU times: total: 6.86 s
Wall time: 7.13 s

## 2.RFE

In [70]:
rfe_model=RFE(estimator=RandomForestClassifier(),n_features_to_select=15)
rfe_model.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=15)

In [73]:
rfe_model.get_support()

array([ True,  True, False, False, False,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False])

In [75]:
X_train_rfe_model = rfe_model.transform(X_train)
X_test_rfe_model = rfe_model.transform(X_test)

In [76]:
X_train_rfe_model.shape,X_test_rfe_model.shape

((24000, 15), (6000, 15))

In [83]:
%%time
RunRandomForestClassifier(X_train,y_train,X_test,y_test) #30 Features

Accuracy Score: 0.8195
Precision Score: 0.6662
Recall Score 0.3397
Confusion Matrix:
 [[4474  222]
 [ 861  443]]
CPU times: total: 7.52 s
Wall time: 8 s

In [87]:
%%time
RunRandomForestClassifier(X_train_rfe_model,y_train,X_test_rfe_model,y_test) #12 Features

Accuracy Score: 0.8248
Precision Score: 0.6937
Recall Score 0.3474
Confusion Matrix:
 [[4496  200]
 [ 851  453]]
CPU times: total: 8.11 s
Wall time: 8.8 s